export const LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const LOGIN_ERROR = 'AUTH_LOGIN_ERROR'
export const FETCH_USER = 'AUTH_FETCH_USER'
export const INITIAL_USER = 'AUTH_INITIAL_USER'
export const USER_CHANGED = 'AUTH_USER_CHANGED'
export const HIJACK_USER = 'AUTH_HIJACK_USER'


//export const INITIAL_USERTBETS = 'USERBETS_INITIAL'
//export const CHANGE_USERBET = 'USERBET_CHANGE'
//export const ADD_USERBET = 'USERBET_ADD'
//export const DELETE_USERBET = 'USERBET_DELETE'


export const INITIAL_CURRENCIES = 'INITIAL_CURRENCIES'
export const CURRENCY_CHANGED = 'CURRENCY_CHANGED'


export const ADD_RACE = 'RACEFEED_ADD'
export const CHANGE_RACE = 'RACEFEED_CHANGE'
export const DELETE_RACE = 'RACEFEED_DELETE'
export const RESET_RACES = 'TRACEEED_RESET'
